* GPS Helper

Based on
[[https://steamcommunity.com/sharedfiles/filedetails/?id=2478246718][GPSHelper]]
by CrazyDave137, seemingly abandoned and non-functional. I picked it up, cleaned
it a bit, and fixed issues with string filtering. Commands are the same, I just
fixed some internals and minor performance issuese that nobody would have
noticed anyway.

Code available on [[https://github.com/mkaito/SE-GPS-Helper][GitHub]].

** Usage

=[string]= denotes an optional parameter. You may provide it, or leave it blank.

When adding a GPS, it will be used as the base name. Omitting will use the
Player name instead.

When filtering, providing an argument will try to do a substring match
('contains') on the GPS name, description, and hexadecimal string representation
of the colour.

- =/gpsx [string]= creates a GPS point at current location, noting the local
  planet in the description. An auto-incrementing hexadecimal auto-ID string is
  appended to uniquely identify each GPS.
- =/gpsx_reset= resets the auto-incrementing auto-ID. Does not modify existing GPS.
- =/gps_export [string]= export all matching GPS to clipboard. No argument exports all GPS.
- =/gps_toggle [string]= toggle visibility of all matching GPS. No argument toggles all GPS.
- =/gps_off [string]= turn visibility of matching GPS off. No argument toggles all GPS.
- =/gps_on [string]= turn visibility of matching GPS on. No argument toggles all GPS.
- =/gps_remove [string]= remove all matching GPS. No argument removes all GPS. *WARNING: Can not be undone!*

** Props

- CrazyDave137 for authoring the original mod
- Digi for putting up with my endless flood of questions and being an all round nice chap